const customers = [
  {
    fName: "Nadeem",
    lName: "Khan",
    add1: "Gandhibagh",
    add2: "Agarsen Sqr",
    street: "Mark Road",
    country: "England",
    city: "Nagpur",
    phone: "9860206440",
    email: "nadim.khan@gmail.com",
    industry: "IT",
    zip: "440018",
  },
  {
    fName: "Vishal",
    lName: "Varma",
    add1: "Gitanjali",
    add2: "West Road",
    street: "Lord street",
    country: "India",
    city: "Lord",
    phone: "976757656",
    email: "visahl@gmail.com",
    industry: "Education",
    zip: "3223523",
  },
  {
    fName: "Amit",
    lName: "Thakur",
    add1: "Aparna Villa",
    add2: "Naer Post Office",
    street: "Prayag Road",
    country: "Newzeland",
    city: "Pune",
    phone: "978657455",
    email: "Amittk@gmail.com",
    industry: "Construction",
    zip: "8675",
  },
  {
    fName: "Mark",
    lName: "Henry",
    add1: "ovile house",
    add2: "Near West villa",
    street: "Street",
    country: "England",
    city: "London",
    phone: "986020",
    email: "markeh@gmail.com",
    industry: "Finance",
    zip: "24224",
  },
  {
    fName: "Vinod",
    lName: "Kamble",
    add1: "Samsthi Pur",
    add2: "Vishal Nagar",
    street: "APJ Street",
    country: "India",
    city: "Nagpur",
    phone: "9787676",
    email: "ndsa@gmail.com",
    industry: "IT",
    zip: "4534454",
  },
  {
    fName: "Javed",
    lName: "Sheikh",
    add1: "Gandhibagh",
    add2: "Loahrpura",
    street: "Central Avenue",
    country: "England",
    city: "Nagpur",
    phone: "9893849384",
    email: "javed@gmail.com",
    industry: "IT",
    zip: "440019",
  },
  {
    fName: "Anurag",
    lName: "Kashyap",
    add1: "Mount Villa",
    add2: "Ganesh Nagar",
    street: "Vanila Street",
    country: "India",
    city: "Mumbai",
    phone: "985654533",
    email: "Anurag@gmail.com",
    industry: "Finance",
    zip: "4534534",
  },
  {
    fName: "Mihan",
    lName: "Varma",
    add1: "gandhibagh",
    add2: "KasturchandPark",
    street: "",
    country: "Russia",
    city: "Nagpur",
    phone: "989384923",
    email: "mihan@gmail.com",
    industry: "Construction",
    zip: "440018",
  },
];

export default customers;
